spring:
    application:
        name: aulao-spring-security
    security:
      oauth2:
        client:
          registration:
            google:
              client-id: 257573337494-0iobucqmlditfs3j5peas11g07bdolo4.apps.googleusercontent.com
              client-secret: 
        resourceserver:
          jwt:
            issuer-uri: https://accounts.google.com

server:
  port: 8080
